### ISSUE TITLE
Annotate $get

### ISSUE THREAD

**Issue by ghost** [mikepugh/AngularGeo#7]
Not sure why this haven't been done yet, but there are errors when uglifying files, or even when using minified distribution files, unless annotations are added.

**Comment by mikepugh** [comment]
@mfc-julius looks like I forgot to include the ngmin task in my build grunt task to generate the *.min.js distro files.

If I have time to work on that this weekend, I'll get that fixed and probably migrate to ngAnnotate since I believe ngmin was deprecated a while back.

**Comment by mfc-julius** [comment]
You could simple add annotations by hand, as some people use not minified source files, and only then apply uglify task via Grunt together with any other concat'ed external library.

**Comment by mikepugh** [comment]
@mfc-julius sorry I haven't had a chance to work on this yet. I'd setup the ngAnnotate task to annotate the non-minified version within the dist/ folder as well. 

FYI - if you are using Grunt along with uglify, you can and should consider using ngAnnotate within the uglify pipeline.
